# Generated by SafeHood setup
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_level', models.PositiveSmallIntegerField(default=1)),
                ('trigger_count', models.PositiveSmallIntegerField(default=1)),
                ('trigger_source', models.CharField(default='unknown', max_length=32)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('resolved', 'Resolved')], default='active', max_length=16)),
                ('live_view_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='alerts.alert')),
            ],
            options={
                'ordering': ['captured_at'],
            },
        ),
    ]